
import { TranslationDictionary } from './types';

export const TRANSLATIONS: TranslationDictionary = {
  en: {
    loginTitle: "Welcome Back",
    loginSubtitle: "Enter your credentials to access the dashboard.",
    loginHeroDesc: "Manage your entire electronics retail empire from one central hub. Track sales, inventory, and staff in real-time.",
    email: "Email Address",
    password: "Password",
    loginBtn: "Sign In",
    dashboard: "Dashboard",
    liveMap: "Live Map",
    users: "Users",
    roles: "Roles",
    permissions: "Permissions",
    customers: "Customers",
    warehouses: "Warehouses",
    stores: "Stores",
    vehicles: "Vehicles",
    drivers: "Drivers",
    merchandisers: "Merchandisers",
    salesManagers: "Sales Managers",
    transfers: "Stock Transfers",
    brands: "Brands",
    categories: "Categories",
    products: "Products",
    settings: "Settings",
    logout: "Logout",
    search: "Search...",
    addUser: "Add User",
    editUser: "Edit User",
    deleteConfirm: "Are you sure you want to delete this item?",
    save: "Save",
    cancel: "Cancel",
    name: "Name",
    role: "Role",
    userType: "User Type",
    status: "Status",
    actions: "Actions",
    active: "Active",
    inactive: "Inactive",
    itemCreated: "Item created successfully",
    itemUpdated: "Item updated successfully",
    itemDeleted: "Item deleted successfully",
    welcome: "Welcome",
    totalUsers: "Total Users",
    activeFleet: "Active Fleet",
    orders: "Orders",
    pending: "Pending",
    productsInactive: "Inactive Products",
    vehiclesTotal: "vehicles total",
    addRole: "Add Role",
    editRole: "Edit Role",
    addPermission: "Add Permission",
    description: "Description",
    permissionsDesc: "Manage system permissions and access rights.",
    rolesDesc: "Define roles and assign permissions to control access.",
    usersDesc: "Manage system users and their access levels.",
    notifications: "Notifications",
    notificationsDesc: "Send and manage system-wide notifications.",
    title: "Title",
    message: "Message",
    targetType: "Target Group",
    readCount: "Read Count",
    date: "Date",
    sendNotification: "Send Notification",
    markAsRead: "Mark as Read",
    allUsers: "All",
    unread: "Unread",
    read: "Read",
    noNotifications: "No notifications found.",
    copyright: "© 2025 ElectroGlobal. All rights reserved.",
    myLocation: "My Location",
    todayRoute: "Today's Route",
    noRouteToday: "No route assigned for today.",
    visitStore: "Visit Store",
    notVisited: "Not Visited",
    visited: "Visited",
    notes: "Notes",
    visitReason: "Reason for skipping",
    submitVisit: "Submit Visit",
    distance: "Distance",
    storeLocation: "Store Location",
    calculating: "Calculating...",
    withinRange: "Within Range",
    outOfRange: "Out of Range",
    getLocation: "Get Location",
    locationError: "Could not get location",
    beforeImages: "Before Images",
    afterImages: "After Images",
    routePlanning: "Route Planning",
    routePlanningDesc: "Assign stores to Sales Managers for weekly visits.",
    selectSalesManager: "Select Sales Manager",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sunday: "Sunday",
    addStoreToDay: "Add Store to Day",
    savePlan: "Save Route Plan",
    planSaved: "Route plan saved successfully",
    selectManagerFirst: "Please select a sales manager first.",
    reports: "Reports",
    reportFilters: "Report Filters",
    startDate: "Start Date",
    endDate: "End Date",
    selectDriver: "Select Driver",
    allDrivers: "All Drivers",
    allMerchandisers: "All Merchandisers",
    vehicleLoadingReports: "Vehicle Loading",
    orderDeliveries: "Order Deliveries",
    productAnalysis: "Product Analysis",
    visitReports: "Visit Reports",
    routeReports: "Route Compliance",
    loadingDate: "Loading Date",
    sourceWarehouse: "Source",
    targetVehicle: "Target Vehicle",
    driver: "Driver",
    productCount: "Items",
    orderId: "Order ID",
    totalAmount: "Amount",
    totalSold: "Total Sold",
    revenue: "Revenue",
    salesVolume: "Sales Volume",
    salesManager: "Sales Manager",
    planned: "Planned",
    actual: "Actual",
    compliance: "Compliance",
    standardUser: "Standard User",
    merchandiser: "Merchandiser",
    linkedEntity: "Linked Profile",
    noLink: "No Link",
    generalSettings: "General",
    apiIntegration: "API Integration",
    appearance: "Appearance",
    systemColor: "System Color",
    fontSize: "Font Size",
    indigo: "Indigo",
    blue: "Blue",
    emerald: "Emerald",
    rose: "Rose",
    amber: "Amber",
    small: "Small",
    medium: "Medium",
    large: "Large",
    currency: "Currency",
    saveSettings: "Save Settings",
    settingsSaved: "Settings saved successfully",
    orderDispatch: "Order Dispatch",
    orderDispatchDesc: "Assign pending orders to vehicles for delivery.",
    unassignedOrders: "Unassigned Orders",
    assignToVehicle: "Assign to Vehicle",
    checkStock: "Check Stock",
    stockMissing: "Stock missing in vehicle",
    createTransfer: "Create transfer automatically",
    stockAvailable: "Stock available",
    transferCreated: "Transfer request created",
    operationSuccess: "Operation successful",
    customerDeliveries: "Customer Deliveries",
    confirmReceipt: "Confirm Delivery",
    confirmReceiptDesc: "Are you sure you have received these items?",
    iHaveReceived: "I Have Received",
    awaitingApproval: "Awaiting Approval",
    completed: "Completed",
    idPhoto: "ID Photo",
    signature: "Signature",
    collectedCash: "Cash Collected",
    collectedCard: "Card Amount",
    failureReason: "Failure Reason",
    customerNotHome: "Customer Not Home",
    vehicleBreakdown: "Vehicle Breakdown",
    customerRefused: "Customer Refused",
    failed: "Failed",
    customer: "Customer",
    items: "Items",
    paymentType: "Payment",
    cod_cash: "Cash on Delivery",
    cod_card: "Card on Delivery",
    cod_mixed: "Mixed Payment",
    online: "Online Payment",
    pendingWarehouse: "Pending Warehouse",
    assignedToDriver: "Assigned to Driver",
    outForDelivery: "Out for Delivery",
    delivered: "Delivered",
    viewOrders: "View Orders",
    viewRoute: "View Route",
    showAll: "Show All",
    driversOnly: "Drivers Only",
    merchandisersOnly: "Merchandisers Only",
    ordersForToday: "Orders Today",
    storeVisitsForToday: "Visits Today",
    stockReport: "Stock Report",
    currentStock: "Current Stock",
    totalValue: "Total Value",
    locationType: "Location Type",
    lowStock: "Low Stock",
    userPassword: "Password",
    location: "Location",
    code: "Code",
    sku: "SKU",
    brand: "Brand",
    category: "Category",
    price: "Price",
    barcode: "Barcode",
    imei: "IMEI",
    serialNumber: "Serial Number",
    addBrand: "Add Brand",
    editBrand: "Edit Brand",
    brandsDesc: "Manage product brands and manufacturers.",
    addCategory: "Add Category",
    editCategory: "Edit Category",
    categoriesDesc: "Manage product categories and hierarchy.",
    addProduct: "Add Product",
    editProduct: "Edit Product",
    productsDesc: "Manage product catalog, prices, and details.",
    addTransfer: "New Transfer",
    editTransfer: "Edit Transfer",
    transfersDesc: "Manage stock movements between warehouses and vehicles.",
    source: "Source",
    target: "Target",
    quantity: "Quantity",
    addItem: "Add Item",
    removeItem: "Remove",
    changePassword: "Change Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    passwordChanged: "Password changed successfully",
    weeklySales: "Weekly Sales",
    viewReport: "View Report",
    recentActivity: "Recent Activity",
    activeRoles: "Active Roles",
    managingPermissions: "Managing {0} permissions",
    lowStockAlerts: "Low Stock Alerts",
    revenueToday: "Revenue Today",
    fromLastMonth: "from last month",
    totalOrdersSmall: "total orders",
    needsAttention: "Needs attention",
    deliveryRate: "Delivery Rate",
    select: "Select...",
    userNotifications: "User Notifications",
    driverAcceptance: "Driver Acceptance",
    administration: "Administration",
    mapView: "Map View",
    listView: "List View",
    navigate: "Navigate"
  },
  az: {
    loginTitle: "Xoş Gəlmisiniz",
    loginSubtitle: "İdarə panelinə daxil olmaq üçün məlumatlarınızı daxil edin.",
    loginHeroDesc: "Elektronika satış şəbəkənizi bir mərkəzdən idarə edin. Satışları, stoku və işçiləri real vaxt rejimində izləyin.",
    email: "E-poçt ünvanı",
    password: "Şifrə",
    loginBtn: "Daxil Ol",
    dashboard: "İdarə Paneli",
    liveMap: "Canlı Xəritə",
    users: "İstifadəçilər",
    roles: "Rolları",
    permissions: "İcazələr",
    customers: "Müştərilər",
    warehouses: "Anbarlar",
    stores: "Mağazalar",
    vehicles: "Nəqliyyat",
    drivers: "Sürücülər",
    merchandisers: "Merçendayzerlər",
    salesManagers: "Satış Menecerləri",
    transfers: "Stok Transferləri",
    brands: "Brendlər",
    categories: "Kateqoriyalar",
    products: "Məhsullar",
    settings: "Tənzimləmələr",
    logout: "Çıxış",
    search: "Axtarış...",
    addUser: "İstifadəçi Əlavə Et",
    editUser: "İstifadəçini Düzəlt",
    deleteConfirm: "Bu elementi silmək istədiyinizə əminsiniz?",
    save: "Yadda Saxla",
    cancel: "Ləğv Et",
    name: "Ad",
    role: "Rol",
    userType: "İstifadəçi Növü",
    status: "Status",
    actions: "Əməliyyatlar",
    active: "Aktiv",
    inactive: "Deaktiv",
    itemCreated: "Element uğurla yaradıldı",
    itemUpdated: "Element uğurla yeniləndi",
    itemDeleted: "Element uğurla silindi",
    welcome: "Xoş Gəldiniz",
    totalUsers: "Cəmi İstifadəçi",
    activeFleet: "Aktiv Donanma",
    orders: "Sifarişlər",
    pending: "Gözləmədə",
    productsInactive: "Deaktiv Məhsullar",
    vehiclesTotal: "cəmi nəqliyyat",
    addRole: "Rol Əlavə Et",
    editRole: "Rolu Düzəlt",
    addPermission: "İcazə Əlavə Et",
    description: "Təsvir",
    permissionsDesc: "Sistem icazələrini və giriş hüquqlarını idarə edin.",
    rolesDesc: "Rolları təyin edin və giriş icazələrini verin.",
    usersDesc: "Sistem istifadəçilərini və onların giriş səviyyələrini idarə edin.",
    notifications: "Bildirişlər",
    notificationsDesc: "Sistem bildirişləri göndərin və idarə edin.",
    title: "Başlıq",
    message: "Mesaj",
    targetType: "Hədəf Qrupu",
    readCount: "Oxunma Sayı",
    date: "Tarix",
    sendNotification: "Bildiriş Göndər",
    markAsRead: "Oxunmuş kimi işarələ",
    allUsers: "Hamısı",
    unread: "Oxunmamış",
    read: "Oxunmuş",
    noNotifications: "Bildiriş tapılmadı.",
    copyright: "© 2025 ElectroGlobal. Bütün hüquqlar qorunur.",
    myLocation: "Mənim Mövqeyim",
    todayRoute: "Bugünkü Marşrut",
    noRouteToday: "Bu gün üçün marşrut təyin edilməyib.",
    visitStore: "Mağazaya Başçəkmə",
    notVisited: "Başçəkilməyib",
    visited: "Başçəkilib",
    notes: "Qeydlər",
    visitReason: "Səbəb",
    submitVisit: "Başçəkməni Təsdiqlə",
    distance: "Məsafə",
    storeLocation: "Mağaza Mövqeyi",
    calculating: "Hesablanır...",
    withinRange: "Məsafə Daxilində",
    outOfRange: "Məsafədən Kənar",
    getLocation: "Mövqeyi Təyin Et",
    locationError: "Mövqe təyin edilə bilmədi",
    beforeImages: "Əvvəlki Şəkillər",
    afterImages: "Sonrakı Şəkillər",
    routePlanning: "Marşrut Planlaması",
    routePlanningDesc: "Satış menecerləri üçün həftəlik mağaza ziyarətlərini planlaşdırın.",
    selectSalesManager: "Satış Meneceri Seçin",
    monday: "Bazar ertəsi",
    tuesday: "Çərşənbə axşamı",
    wednesday: "Çərşənbə",
    thursday: "Cümə axşamı",
    friday: "Cümə",
    saturday: "Şənbə",
    sunday: "Bazar",
    addStoreToDay: "Günə Mağaza Əlavə Et",
    savePlan: "Planı Yadda Saxla",
    planSaved: "Marşrut planı uğurla yadda saxlanıldı",
    selectManagerFirst: "Əvvəlcə satış meneceri seçin.",
    reports: "Hesabatlar",
    reportFilters: "Hesabat Filtrləri",
    startDate: "Başlanğıc Tarixi",
    endDate: "Bitmə Tarixi",
    selectDriver: "Sürücü Seçin",
    allDrivers: "Bütün Sürücülər",
    allMerchandisers: "Bütün Merçendayzerlər",
    vehicleLoadingReports: "Nəqliyyat Yükləmə",
    orderDeliveries: "Sifariş Çatdırılmaları",
    productAnalysis: "Məhsul Analizi",
    visitReports: "Ziyarət Hesabatları",
    routeReports: "Marşrut Uyğunluğu",
    loadingDate: "Yükləmə Tarixi",
    sourceWarehouse: "Mənbə",
    targetVehicle: "Hədəf Nəqliyyat",
    driver: "Sürücü",
    productCount: "Məhsul Sayı",
    orderId: "Sifariş ID",
    totalAmount: "Məbləğ",
    totalSold: "Cəmi Satılıb",
    revenue: "Gəlir",
    salesVolume: "Satış Həcmi",
    salesManager: "Satış Meneceri",
    planned: "Planlaşdırılan",
    actual: "Faktiki",
    compliance: "Uyğunluq",
    standardUser: "Standart İstifadəçi",
    merchandiser: "Merçendayzer",
    linkedEntity: "Əlaqəli Profil",
    noLink: "Əlaqə Yoxdur",
    generalSettings: "Ümumi",
    apiIntegration: "API İnteqrasiyası",
    appearance: "Görünüş",
    systemColor: "Sistem Rəngi",
    fontSize: "Şrift Ölçüsü",
    indigo: "İndiqo",
    blue: "Mavi",
    emerald: "Zümrüd",
    rose: "Qızılgül",
    amber: "Kəhrəba",
    small: "Kiçik",
    medium: "Orta",
    large: "Böyük",
    currency: "Valyuta",
    saveSettings: "Tənzimləmələri Saxla",
    settingsSaved: "Tənzimləmələr uğurla saxlanıldı",
    orderDispatch: "Sifariş Paylanması",
    orderDispatchDesc: "Gözləyən sifarişləri çatdırılma üçün nəqliyyat vasitələrinə təyin edin.",
    unassignedOrders: "Təyin Edilməmiş Sifarişlər",
    assignToVehicle: "Nəqliyyata Təyin Et",
    checkStock: "Stoku Yoxla",
    stockMissing: "Nəqliyyatda stok çatışmır",
    createTransfer: "Avtomatik transfer yarat",
    stockAvailable: "Stok mövcuddur",
    transferCreated: "Transfer sorğusu yaradıldı",
    operationSuccess: "Əməliyyat uğurludur",
    customerDeliveries: "Müştəri Çatdırılmaları",
    confirmReceipt: "Qəbunu Təsdiqlə",
    confirmReceiptDesc: "Bu məhsulları qəbul etdiyinizə əminsiniz?",
    iHaveReceived: "Qəbul Etdim",
    awaitingApproval: "Təsdiq Gözləyir",
    completed: "Tamamlandı",
    idPhoto: "Şəxsiyyət Vəsiqəsi",
    signature: "İmza",
    collectedCash: "Nəğd Məbləğ",
    collectedCard: "Kart Məbləği",
    failureReason: "Uğursuzluq Səbəbi",
    customerNotHome: "Müştəri Evdə Yoxdur",
    vehicleBreakdown: "Nəqliyyat Nasazlığı",
    customerRefused: "Müştəri İmtina Etdi",
    failed: "Uğursuz",
    customer: "Müştəri",
    items: "Məhsullar",
    paymentType: "Ödəniş",
    cod_cash: "Qapıda Nəğd",
    cod_card: "Qapıda Kartla",
    cod_mixed: "Qarışıq Ödəniş",
    online: "Onlayn Ödəniş",
    pendingWarehouse: "Anbarda Gözləyir",
    assignedToDriver: "Sürücüyə Verildi",
    outForDelivery: "Çatdırılmadadır",
    delivered: "Çatdırıldı",
    viewOrders: "Sifarişlərə Bax",
    viewRoute: "Marşruta Bax",
    showAll: "Hamısını Göstər",
    driversOnly: "Yalnız Sürücülər",
    merchandisersOnly: "Yalnız Merçendayzerlər",
    ordersForToday: "Bugünkü Sifarişlər",
    storeVisitsForToday: "Bugünkü Ziyarətlər",
    stockReport: "Stok Hesabatı",
    currentStock: "Cari Stok",
    totalValue: "Ümumi Dəyər",
    locationType: "Məkan Növü",
    lowStock: "Aşağı Stok",
    userPassword: "Şifrə",
    location: "Məkan",
    code: "Kod",
    sku: "SKU",
    brand: "Brend",
    category: "Kateqoriya",
    price: "Qiymət",
    barcode: "Barkod",
    imei: "İMEİ",
    serialNumber: "Seriya Nömrəsi",
    addBrand: "Brend Əlavə Et",
    editBrand: "Brender Düzəlt",
    brandsDesc: "Məhsul brendlərini və istehsalçılarını idarə edin.",
    addCategory: "Kateqoriya Əlavə Et",
    editCategory: "Kateqoriyanı Düzəlt",
    categoriesDesc: "Məhsul kateqoriyalarını və iyerarxiyanı idarə edin.",
    addProduct: "Məhsul Əlavə Et",
    editProduct: "Məhsulu Düzəlt",
    productsDesc: "Məhsul kataloqunu, qiymətləri və detalları idarə edin.",
    addTransfer: "Yeni Transfer",
    editTransfer: "Transferi Düzəlt",
    transfersDesc: "Anbarlar və nəqliyyat vasitələri arasında stok hərəkətlərini idarə edin.",
    source: "Mənbə",
    target: "Hədəf",
    quantity: "Say",
    addItem: "Məhsul Əlavə Et",
    removeItem: "Sil",
    changePassword: "Şifrəni Dəyiş",
    newPassword: "Yeni Şifrə",
    confirmPassword: "Şifrəni Təsdiqlə",
    passwordChanged: "Şifrə uğurla dəyişdirildi",
    weeklySales: "Həftəlik Satışlar",
    viewReport: "Hesabata Bax",
    recentActivity: "Son Fəaliyyətlər",
    activeRoles: "Aktiv Rollar",
    managingPermissions: "{0} icazə idarə olunur",
    lowStockAlerts: "Stok Xəbərdarlığı",
    revenueToday: "Bugünkü Gəlir",
    fromLastMonth: "keçən aydan",
    totalOrdersSmall: "cəmi sifariş",
    needsAttention: "Diqqət tələb edir",
    deliveryRate: "Çatdırılma Faizi",
    select: "Seçin...",
    userNotifications: "İstifadəçi Bildirişləri",
    driverAcceptance: "Sürücü Qəbulu",
    administration: "İdarəetmə",
    mapView: "Xəritə Görüntüsü",
    listView: "Siyahı Görüntüsü",
    navigate: "Naviqasiya"
  },
  tr: {
    loginTitle: "Tekrar Hoşgeldiniz",
    loginSubtitle: "Kontrol paneline erişmek için bilgilerinizi girin.",
    loginHeroDesc: "Tüm elektronik perakende imparatorluğunuzu tek bir merkezden yönetin. Satışları, stoku ve personeli gerçek zamanlı takip edin.",
    email: "E-posta Adresi",
    password: "Şifre",
    loginBtn: "Giriş Yap",
    dashboard: "Kontrol Paneli",
    liveMap: "Canlı Harita",
    users: "Kullanıcılar",
    roles: "Roller",
    permissions: "İzinler",
    customers: "Müşteriler",
    warehouses: "Depolar",
    stores: "Mağazalar",
    vehicles: "Araçlar",
    drivers: "Sürücüler",
    merchandisers: "Merçendayzerler",
    salesManagers: "Satış Müdürleri",
    transfers: "Stok Transferleri",
    brands: "Markalar",
    categories: "Kategoriler",
    products: "Ürünler",
    settings: "Ayarlar",
    logout: "Çıkış",
    search: "Ara...",
    addUser: "Kullanıcı Ekle",
    editUser: "Kullanıcı Düzenle",
    deleteConfirm: "Bu öğeyi silmek istediğinizden emin misiniz?",
    save: "Kaydet",
    cancel: "İptal",
    name: "Ad",
    role: "Rol",
    userType: "Kullanıcı Tipi",
    status: "Durum",
    actions: "İşlemler",
    active: "Aktif",
    inactive: "Pasif",
    itemCreated: "Öğe başarıyla oluşturuldu",
    itemUpdated: "Öğe başarıyla güncellendi",
    itemDeleted: "Öğe başarıyla silindi",
    welcome: "Hoşgeldiniz",
    totalUsers: "Toplam Kullanıcı",
    activeFleet: "Aktif Filo",
    orders: "Siparişler",
    pending: "Beklemede",
    productsInactive: "Pasif Ürünler",
    vehiclesTotal: "toplam araç",
    addRole: "Rol Ekle",
    editRole: "Rol Düzenle",
    addPermission: "İzin Ekle",
    description: "Açıklama",
    permissionsDesc: "Sistem izinlerini ve erişim haklarını yönetin.",
    rolesDesc: "Rolleri tanımlayın ve erişim izinlerini atayın.",
    usersDesc: "Sistem kullanıcılarını ve erişim seviyelerini yönetin.",
    notifications: "Bildirimler",
    notificationsDesc: "Sistem genelinde bildirim gönderin ve yönetin.",
    title: "Başlık",
    message: "Mesaj",
    targetType: "Hedef Grubu",
    readCount: "Okunma Sayısı",
    date: "Tarih",
    sendNotification: "Bildirim Gönder",
    markAsRead: "Okundu Olarak İşaretle",
    allUsers: "Tümü",
    unread: "Okunmamış",
    read: "Okunmuş",
    noNotifications: "Bildirim bulunamadı.",
    copyright: "© 2025 ElectroGlobal. Tüm hakları saklıdır.",
    myLocation: "Konumum",
    todayRoute: "Bugünkü Rota",
    noRouteToday: "Bugün için rota atanmamış.",
    visitStore: "Mağazayı Ziyaret Et",
    notVisited: "Ziyaret Edilmedi",
    visited: "Ziyaret Edildi",
    notes: "Notlar",
    visitReason: "Sebep",
    submitVisit: "Ziyareti Gönder",
    distance: "Mesafe",
    storeLocation: "Mağaza Konumu",
    calculating: "Hesaplanıyor...",
    withinRange: "Mesafe İçinde",
    outOfRange: "Mesafe Dışında",
    getLocation: "Konumu Al",
    locationError: "Konum alınamadı",
    beforeImages: "Önceki Resimler",
    afterImages: "Sonraki Resimler",
    routePlanning: "Rota Planlama",
    routePlanningDesc: "Satış Müdürleri için haftalık mağaza ziyaretlerini planlayın.",
    selectSalesManager: "Satış Müdürü Seçin",
    monday: "Pazartesi",
    tuesday: "Salı",
    wednesday: "Çarşamba",
    thursday: "Perşembe",
    friday: "Cuma",
    saturday: "Cumartesi",
    sunday: "Pazar",
    addStoreToDay: "Güne Mağaza Ekle",
    savePlan: "Planı Kaydet",
    planSaved: "Rota planı başarıyla kaydedildi",
    selectManagerFirst: "Lütfen önce bir satış müdürü seçin.",
    reports: "Raporlar",
    reportFilters: "Rapor Filtreleri",
    startDate: "Başlangıç Tarihi",
    endDate: "Bitiş Tarihi",
    selectDriver: "Sürücü Seçin",
    allDrivers: "Tüm Sürücüler",
    allMerchandisers: "Tüm Merçendayzerler",
    vehicleLoadingReports: "Araç Yükleme",
    orderDeliveries: "Sipariş Teslimatları",
    productAnalysis: "Ürün Analizi",
    visitReports: "Ziyaret Raporları",
    routeReports: "Rota Uyumu",
    loadingDate: "Yükleme Tarihi",
    sourceWarehouse: "Kaynak",
    targetVehicle: "Hedef Araç",
    driver: "Sürücü",
    productCount: "Ürün Sayısı",
    orderId: "Sipariş ID",
    totalAmount: "Tutar",
    totalSold: "Toplam Satılan",
    revenue: "Gelir",
    salesVolume: "Satış Hacmi",
    salesManager: "Satış Müdürü",
    planned: "Planlanan",
    actual: "Gerçekleşen",
    compliance: "Uyum",
    standardUser: "Standart Kullanıcı",
    merchandiser: "Merçendayzer",
    linkedEntity: "Bağlı Profil",
    noLink: "Bağlantı Yok",
    generalSettings: "Genel",
    apiIntegration: "API Entegrasyonu",
    appearance: "Görünüm",
    systemColor: "Sistem Rengi",
    fontSize: "Yazı Boyutu",
    indigo: "İndigo",
    blue: "Mavi",
    emerald: "Zümrüt",
    rose: "Gül",
    amber: "Kehribar",
    small: "Küçük",
    medium: "Orta",
    large: "Büyük",
    currency: "Para Birimi",
    saveSettings: "Ayarları Kaydet",
    settingsSaved: "Ayarlar başarıyla kaydedildi",
    orderDispatch: "Sipariş Dağıtımı",
    orderDispatchDesc: "Bekleyen siparişleri teslimat için araçlara atayın.",
    unassignedOrders: "Atanmamış Siparişler",
    assignToVehicle: "Araca Ata",
    checkStock: "Stok Kontrol",
    stockMissing: "Araçta stok eksik",
    createTransfer: "Otomatik transfer oluştur",
    stockAvailable: "Stok mevcut",
    transferCreated: "Transfer isteği oluşturuldu",
    operationSuccess: "İşlem başarılı",
    customerDeliveries: "Müşteri Teslimatları",
    confirmReceipt: "Teslimatı Onayla",
    confirmReceiptDesc: "Bu ürünleri teslim aldığınızdan emin misiniz?",
    iHaveReceived: "Teslim Aldım",
    awaitingApproval: "Onay Bekliyor",
    completed: "Tamamlandı",
    idPhoto: "Kimlik Fotoğrafı",
    signature: "İmza",
    collectedCash: "Nakit Tahsilat",
    collectedCard: "Kart Tahsilatı",
    failureReason: "Başarısızlık Nedeni",
    customerNotHome: "Müşteri Evde Yok",
    vehicleBreakdown: "Araç Arızası",
    customerRefused: "Müşteri Reddetti",
    failed: "Başarısız",
    customer: "Müşteri",
    items: "Ürünler",
    paymentType: "Ödeme",
    cod_cash: "Kapıda Nakit",
    cod_card: "Kapıda Kart",
    cod_mixed: "Karışık Ödeme",
    online: "Online Ödeme",
    pendingWarehouse: "Depoda Bekliyor",
    assignedToDriver: "Sürücüye Atandı",
    outForDelivery: "Dağıtımda",
    delivered: "Teslim Edildi",
    viewOrders: "Siparişleri Gör",
    viewRoute: "Rotayı Gör",
    showAll: "Tümünü Göster",
    driversOnly: "Sadece Sürücüler",
    merchandisersOnly: "Sadece Merçendayzerler",
    ordersForToday: "Bugünkü Siparişler",
    storeVisitsForToday: "Bugünkü Ziyaretler",
    stockReport: "Stok Raporu",
    currentStock: "Mevcut Stok",
    totalValue: "Toplam Değer",
    locationType: "Konum Tipi",
    lowStock: "Düşük Stok",
    userPassword: "Şifre",
    location: "Konum",
    code: "Kod",
    sku: "SKU",
    brand: "Marka",
    category: "Kategori",
    price: "Fiyat",
    barcode: "Barkod",
    imei: "IMEI",
    serialNumber: "Seri Numarası",
    addBrand: "Marka Ekle",
    editBrand: "Marka Düzenle",
    brandsDesc: "Ürün markalarını ve üreticilerini yönetin.",
    addCategory: "Kategori Ekle",
    editCategory: "Kategori Düzenle",
    categoriesDesc: "Ürün kategorilerini ve hiyerarşiyi yönetin.",
    addProduct: "Ürün Ekle",
    editProduct: "Ürün Düzenle",
    productsDesc: "Ürün kataloğunu, fiyatları ve detayları yönetin.",
    addTransfer: "Yeni Transfer",
    editTransfer: "Transfer Düzenle",
    transfersDesc: "Depolar ve araçlar arası stok hareketlerini yönetin.",
    source: "Kaynak",
    target: "Hedef",
    quantity: "Miktar",
    addItem: "Ürün Ekle",
    removeItem: "Kaldır",
    changePassword: "Şifre Değiştir",
    newPassword: "Yeni Şifre",
    confirmPassword: "Şifre Onayla",
    passwordChanged: "Şifre başarıyla değiştirildi",
    weeklySales: "Haftalık Satışlar",
    viewReport: "Raporu Gör",
    recentActivity: "Son Aktiviteler",
    activeRoles: "Aktif Roller",
    managingPermissions: "{0} izin yönetiliyor",
    lowStockAlerts: "Düşük Stok Uyarıları",
    revenueToday: "Bugünkü Gelir",
    fromLastMonth: "geçen aydan",
    totalOrdersSmall: "toplam sipariş",
    needsAttention: "İlgi bekliyor",
    deliveryRate: "Teslimat Oranı",
    select: "Seçiniz...",
    userNotifications: "Kullanıcı Bildirimleri",
    driverAcceptance: "Sürücü Kabulü",
    administration: "Yönetim",
    mapView: "Harita Görünümü",
    listView: "Liste Görünümü",
    navigate: "Yol Tarifi"
  },
  ru: {
    loginTitle: "Добро пожаловать",
    loginSubtitle: "Введите свои данные для доступа к панели управления.",
    loginHeroDesc: "Управляйте всей сетью розничной торговли электроникой из одного центра. Отслеживайте продажи, запасы и персонал в реальном времени.",
    email: "Электронная почта",
    password: "Пароль",
    loginBtn: "Войти",
    dashboard: "Панель",
    liveMap: "Живая Карта",
    users: "Пользователи",
    roles: "Роли",
    permissions: "Разрешения",
    customers: "Клиенты",
    warehouses: "Склады",
    stores: "Магазины",
    vehicles: "Транспорт",
    drivers: "Водители",
    merchandisers: "Мерчендайзеры",
    salesManagers: "Менеджеры по продажам",
    transfers: "Перемещение запасов",
    brands: "Бренды",
    categories: "Категории",
    products: "Продукты",
    settings: "Настройки",
    logout: "Выйти",
    search: "Поиск...",
    addUser: "Добавить пользователя",
    editUser: "Редактировать пользователя",
    deleteConfirm: "Вы уверены, что хотите удалить этот элемент?",
    save: "Сохранить",
    cancel: "Отмена",
    name: "Имя",
    role: "Роль",
    userType: "Тип пользователя",
    status: "Статус",
    actions: "Действия",
    active: "Активный",
    inactive: "Неактивный",
    itemCreated: "Элемент успешно создан",
    itemUpdated: "Элемент успешно обновлен",
    itemDeleted: "Элемент успешно удален",
    welcome: "Добро пожаловать",
    totalUsers: "Всего пользователей",
    activeFleet: "Активный автопарк",
    orders: "Заказы",
    pending: "В ожидании",
    productsInactive: "Неактивные продукты",
    vehiclesTotal: "всего машин",
    addRole: "Добавить роль",
    editRole: "Редактировать роль",
    addPermission: "Добавить разрешение",
    description: "Описание",
    permissionsDesc: "Управление системными разрешениями и правами доступа.",
    rolesDesc: "Определите роли и назначьте права доступа.",
    usersDesc: "Управление пользователями системы и их уровнями доступа.",
    notifications: "Уведомления",
    notificationsDesc: "Отправка и управление системными уведомлениями.",
    title: "Заголовок",
    message: "Сообщение",
    targetType: "Целевая группа",
    readCount: "Прочтений",
    date: "Дата",
    sendNotification: "Отправить уведомление",
    markAsRead: "Отметить как прочитанное",
    allUsers: "Все",
    unread: "Непрочитанные",
    read: "Прочитанные",
    noNotifications: "Уведомлений не найдено.",
    copyright: "© 2025 ElectroGlobal. Все права защищены.",
    myLocation: "Мое местоположение",
    todayRoute: "Маршрут на сегодня",
    noRouteToday: "На сегодня маршрут не назначен.",
    visitStore: "Посетить магазин",
    notVisited: "Не посещено",
    visited: "Посещено",
    notes: "Заметки",
    visitReason: "Причина",
    submitVisit: "Отправить посещение",
    distance: "Расстояние",
    storeLocation: "Расположение магазина",
    calculating: "Вычисление...",
    withinRange: "В радиусе",
    outOfRange: "Вне радиуса",
    getLocation: "Получить местоположение",
    locationError: "Не удалось получить местоположение",
    beforeImages: "Фото до",
    afterImages: "Фото после",
    routePlanning: "Планирование маршрута",
    routePlanningDesc: "Назначьте магазины менеджерам по продажам для еженедельных посещений.",
    selectSalesManager: "Выберите менеджера по продажам",
    monday: "Понедельник",
    tuesday: "Вторник",
    wednesday: "Среда",
    thursday: "Четверг",
    friday: "Пятница",
    saturday: "Суббота",
    sunday: "Воскресенье",
    addStoreToDay: "Добавить магазин на день",
    savePlan: "Сохранить план",
    planSaved: "План маршрута успешно сохранен",
    selectManagerFirst: "Пожалуйста, сначала выберите менеджера по продажам.",
    reports: "Отчеты",
    reportFilters: "Фильтры отчетов",
    startDate: "Дата начала",
    endDate: "Дата окончания",
    selectDriver: "Выберите водителя",
    allDrivers: "Все водители",
    allMerchandisers: "Все мерчендайзеры",
    vehicleLoadingReports: "Загрузка транспорта",
    orderDeliveries: "Доставки заказов",
    productAnalysis: "Анализ продуктов",
    visitReports: "Отчеты о посещениях",
    routeReports: "Соблюдение маршрута",
    loadingDate: "Дата загрузки",
    sourceWarehouse: "Источник",
    targetVehicle: "Целевой транспорт",
    driver: "Водитель",
    productCount: "Кол-во товаров",
    orderId: "ID заказа",
    totalAmount: "Сумма",
    totalSold: "Всего продано",
    revenue: "Выручка",
    salesVolume: "Объем продаж",
    salesManager: "Менеджер по продажам",
    planned: "Запланировано",
    actual: "Фактически",
    compliance: "Соблюдение",
    standardUser: "Стандартный пользователь",
    merchandiser: "Мерчендайзер",
    linkedEntity: "Связанный профиль",
    noLink: "Нет связи",
    generalSettings: "Общие",
    apiIntegration: "Интеграция API",
    appearance: "Внешний вид",
    systemColor: "Системный цвет",
    fontSize: "Размер шрифта",
    indigo: "Индиго",
    blue: "Синий",
    emerald: "Изумрудный",
    rose: "Розовый",
    amber: "Янтарный",
    small: "Маленький",
    medium: "Средний",
    large: "Большой",
    currency: "Валюта",
    saveSettings: "Сохранить настройки",
    settingsSaved: "Настройки успешно сохранены",
    orderDispatch: "Распределение заказов",
    orderDispatchDesc: "Назначьте ожидающие заказы на транспортные средства для доставки.",
    unassignedOrders: "Нераспределенные заказы",
    assignToVehicle: "Назначить на транспорт",
    checkStock: "Проверить запас",
    stockMissing: "Нехватка запаса в транспорте",
    createTransfer: "Создать перемещение автоматически",
    stockAvailable: "Запас доступен",
    transferCreated: "Запрос на перемещение создан",
    operationSuccess: "Операция успешна",
    customerDeliveries: "Доставки клиентам",
    confirmReceipt: "Подтвердить получение",
    confirmReceiptDesc: "Вы уверены, что получили эти товары?",
    iHaveReceived: "Я получил",
    awaitingApproval: "Ожидает подтверждения",
    completed: "Завершено",
    idPhoto: "Фото удостоверения",
    signature: "Подпись",
    collectedCash: "Собрано наличными",
    collectedCard: "Сумма по карте",
    failureReason: "Причина неудачи",
    customerNotHome: "Клиента нет дома",
    vehicleBreakdown: "Поломка транспорта",
    customerRefused: "Клиент отказался",
    failed: "Неудачно",
    customer: "Клиент",
    items: "Товары",
    paymentType: "Оплата",
    cod_cash: "Наличными при доставке",
    cod_card: "Картой при доставке",
    cod_mixed: "Смешанная оплата",
    online: "Онлайн оплата",
    pendingWarehouse: "Ожидает на складе",
    assignedToDriver: "Назначено водителю",
    outForDelivery: "В доставке",
    delivered: "Доставлено",
    viewOrders: "Просмотр заказов",
    viewRoute: "Просмотр маршрута",
    showAll: "Показать все",
    driversOnly: "Только водители",
    merchandisersOnly: "Только мерчендайзеры",
    ordersForToday: "Заказы на сегодня",
    storeVisitsForToday: "Посещения сегодня",
    stockReport: "Отчет о запасах",
    currentStock: "Текущий запас",
    totalValue: "Общая стоимость",
    locationType: "Тип места",
    lowStock: "Низкий запас",
    userPassword: "Пароль",
    location: "Место",
    code: "Код",
    sku: "Артикул",
    brand: "Бренд",
    category: "Категория",
    price: "Цена",
    barcode: "Штрихкод",
    imei: "IMEI",
    serialNumber: "Серийный номер",
    addBrand: "Добавить бренд",
    editBrand: "Редактировать бренд",
    brandsDesc: "Управление брендами продуктов и производителями.",
    addCategory: "Добавить категорию",
    editCategory: "Редактировать категорию",
    categoriesDesc: "Управление категориями продуктов и иерархией.",
    addProduct: "Добавить продукт",
    editProduct: "Редактировать продукт",
    productsDesc: "Управление каталогом продуктов, ценами и деталями.",
    addTransfer: "Новое перемещение",
    editTransfer: "Редактировать перемещение",
    transfersDesc: "Управление движением запасов между складами и транспортом.",
    source: "Источник",
    target: "Цель",
    quantity: "Количество",
    addItem: "Добавить товар",
    removeItem: "Удалить",
    changePassword: "Изменить пароль",
    newPassword: "Новый пароль",
    confirmPassword: "Подтвердить пароль",
    passwordChanged: "Пароль успешно изменен",
    weeklySales: "Еженедельные продажи",
    viewReport: "Просмотр отчета",
    recentActivity: "Недавняя активность",
    activeRoles: "Активные роли",
    managingPermissions: "Управление {0} разрешениями",
    lowStockAlerts: "Предупреждения о низком запасе",
    revenueToday: "Выручка сегодня",
    fromLastMonth: "с прошлого месяца",
    totalOrdersSmall: "всего заказов",
    needsAttention: "Требует внимания",
    deliveryRate: "Уровень доставки",
    select: "Выберите...",
    userNotifications: "Уведомления пользователей",
    driverAcceptance: "Приемка водителем",
    administration: "Администрирование",
    mapView: "Карта",
    listView: "Список",
    navigate: "Навигация"
  }
};
